// Generated by CoffeeScript 1.3.3

/*
  测试 mysql 适配器
*/


(function() {
  var Role, User, connection, mysql,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  mysql = require('../index').mysql_native;

  connection = mysql.create_connection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'test'
  });

  User = (function(_super) {

    __extends(User, _super);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.prototype.table_name = 'user';

    User.prototype.connection = connection;

    return User;

  })(mysql);

  Role = (function(_super) {

    __extends(Role, _super);

    function Role() {
      return Role.__super__.constructor.apply(this, arguments);
    }

    Role.prototype.table_name = 'role';

    Role.prototype.connection = connection;

    return Role;

  })(mysql);

  User.find('@.id = ?', 28).as('U').join(Role.as('R'), '@.role_id = R.id').select('@.id , @.name , R.name as role_name').page(1, 3).get_pagination(function(page_info) {
    return console.log(page_info);
  });

}).call(this);
