// Generated by CoffeeScript 1.3.3
(function() {
  var Query, Sex, User, user,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Query = require('../index.js');

  User = (function(_super) {

    __extends(User, _super);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.prototype.table_name = 'user';

    return User;

  })(Query);

  Sex = (function(_super) {

    __extends(Sex, _super);

    function Sex() {
      return Sex.__super__.constructor.apply(this, arguments);
    }

    Sex.prototype.table_name = 'sex';

    return Sex;

  })(Query);

  user = User.find('id = ?', 1).remove();

  console.log(user.to_sql());

  console.log(user._args);

}).call(this);
