// Generated by CoffeeScript 1.4.0
(function() {

  exports.mysql = require('./adapters/mysql');

  exports.mariasql = require('./adapters/maria-pool');

  exports.mysql_native = require('./adapters/mysql_native');

}).call(this);
