// Generated by CoffeeScript 1.3.3
(function() {
  var Query, exports, mysql,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Query = require('../query');

  /*
  node-mysql 适配合器
  @link https://github.com/felixge/node-mysql
  @install npm install mysql@2.0.0-alpha3 
  or npm install git://github.com/felixge/node-mysql.git
  */


  mysql = (function(_super) {

    __extends(mysql, _super);

    function mysql() {
      return mysql.__super__.constructor.apply(this, arguments);
    }

    mysql.prototype.connection = false;

    mysql.create_connection = require('mysql').createConnection;

    mysql.prototype.adapter = function(sql, args, callback) {
      if (this.connection) {
        return this.connection.query(sql, args, function(err, row) {
          if (row == null) {
            row = false;
          }
          return callback(row, err);
        });
      }
    };

    return mysql;

  })(Query);

  exports = module.exports = mysql;

}).call(this);
